config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from posts.views import index,url_view, url_parameter_view, function_view, class_view,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('url',url_view),
    path('url/<str:username>/',url_parameter_view),
    path('fbv/',function_view),
    path('cbv/',class_view.as_view()),
    path('',index,name='index'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('__debug__',include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view,post_delete_view,post_detail_view,post_update_view

app_name='posts'
urlpatterns = [
    path('', post_list_view,name='post-list'),
    path('new/',post_create_view,name='post-create'),
    path('<int:id>/delete/',post_delete_view,name='post-deldete'),
    path('<int:id>/',post_detail_view,name='post-detail'),
    path('<int:id>/edit/',post_update_view,name='post-update'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
#이미지, 조회수, 작성자, 내용, 날짜
User=get_user_model()
class Post(models.Model):
    image=models.ImageField(verbose_name='이미지',null=True,blank=True)
    content=models.TextField(verbose_name='내용')
    created_at=models.DateTimeField(verbose_name='작성일',auto_now_add=True)
    view_count=models.IntegerField(verbose_name='조회수',default=0)
    writer=models.ForeignKey(to=User,on_delete=models.CASCADE,null=True,blank=True)
#댓글 모델 만들어보기 / 내용,작성일, 게시글 ,작성자
class Comment(models.Model):
    content=models.TextField(verbose_name='내용')
    created_at=models.DateTimeField(verbose_name='작성일')
    post=models.ForeignKey(to='Post',on_delete=models.CASCADE)
    writer=models.ForeignKey(to=User,on_delete=models.CASCADE,null=True,blank=True)

# Create your models here.

posts/views.py
from django.shortcuts import render,redirect,get
from django.http import HttpResponse,JsonResponse
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from .models import Post
# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    context={
        'post_list':post_list,
    }
    return render(request,'index.html')

def post_list_view(request):
    #post_list = Post.objects.all()
    post_list = Post.objects.filter(writer=request.user)
    #post_list=None
    context={
        'post_list':post_list,
    }
    return render(request,'posts/post_list.html')

def post_detail_view(request,id):
    try:
        post=Post.objects.get(id=id)
    except Post.DoesNotExist:
        return redirect('index')

    context={
        'post':post,
    }
    return render(request,'posts/post_detail.html')

@login_required
def post_create_view(request):
    if(request.method == 'GET'):
        return render(request,'posts/post_form.html')
    else:
        image=request.FILES.get('image')
        content=request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(
            image=image,
            content=content,
            writer=request.user
        )
        return redirect('index')
    
def post_update_view(request,id):
    post = Post.objects.get(id=id)
    #post = get_object_or_404(Post,id=id)

    if request.method == 'GET':
        context = {
            'post': post
        }
        return render(request, 'posts/post_form.html', context)
    else:
        new_image = request.FILES.get('image')
        content = request.POST.get('content')

        if new_image:
            post.image.delete()
            post.image = new_image

        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)
    
@login_required
def post_delete_view(request,id):
    post=get_object_or_404(Post,id=id)
    if request.user !=post.writer:
        return Http404('잘못된 접근입니다')
    if request.method=='GET':
        context={'post':post}
        return render(request,'posts/post_confirm_delete.html')
    else:
        post.delete()
        return redirect('index')
    
    
def url_view(request):
    print('url_view()')
    data={'code':'001','msg':'OK'}
    #return HttpResponse('<h1>url_view</h1>')
    return JsonResponse(data)

def url_parameter_view(request,username):
    print('url_parameter_view()')
    print(f'username:{username}')
    print(f'request.GET:{request.GET}')
    return HttpResponse(username)

def  function_view(request):
    print(f'request.method:{request.method}')
    if request.method=='GET':
        print(f'request.GET:{request.GET}')
    elif request.method=='POST':
        print(f'request.POST:{request.POST}')
    return render(request,'view.html')

class class_view(ListView):
    model=Post
    template_name='cbv_view.html'
    ordering=['-id']

posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        {{object}}
    {% endfor %}
</body>
</html>

posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/fbv/">새로고침</a><br>
    <form action=""method="GET">
        <input type="text"name="var">
        <input type="submit"value="GET 제출">
    </form>

    <form action=""method="POST">{% csrf_token %}
        <input type="text"name="var">
        <input type="submit"value="POST 제출">
    </form>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body>
    <div>
        {% block content %}
        {% endblock}
    </div>

    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <img src="{% stacic 'icons\home_black_36dp.svg' %}" alt="홈">
                    
                </li>
                <li>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색"/>
                </li>
                <li>
                    <a href="{% url 'posts:post-create' %}">
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="글쓰기"/>
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                </li>
                <li>
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="프로필"/>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}홈{% endblock %}

{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False %}
        {% endfor %}
    </div>
</main>
{% endblock %}

templates/mixin/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img class="card__user-image" src="http://via.placeholder.com/32x32"alt="프로필 이미지">
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>

    </div>
    <div class="card__body">
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}" alt="">
            {% else %}
                <img class="card__image" src="http://via.placeholder.com/600x600" alt="">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글"/>
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기"/>
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크"/>
            </div>
        </div>
        <div class="card_content">
            <span class="card__like-num">좋아요 00개</span>
            <div class="card__main-text">
                <p><span class="card__user-name">{{ post.writer }}</span>{{ post.content |truncatechars:35 }}</p>
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
                {% endif %}
            </div>
            <div>
                <p class="">댓글 {{ post.comment_set.all.count }}개 {% if not detail %}모두 보기{% endif %}</p>
                <ul class="card__comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all %}
                            <li><p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                            </li>
                        {% empty %}
                            <li><p>댓글 없음</p></li>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all|slice:":2" %}
                            <li><p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                            </li>
                        {% empty %}
                            <li><p>댓글 없음</p></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <span class="card__created-at">{{ post.created_at|date:"Y년 m월 d일" }}</span>
        </div>
    </div>
</div>

templates/post/post_confirm_delete.html
{%extends 'base.html' %}
{% block title %}글삭제{% endblock %}

{% block content %}
<h1>Post 삭제화면</h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>한번 삭제된 데이터는 복구가 불가능합니다.</p><br/>
    <p>그래도 삭제하시겠습니까? ID : {{ post.id }}</p><br/><br/>

    <a href="{% url 'index' %}">돌아가기</a>
    <input type="submit" value="삭제하기">
</form>
<hr>
{% endblock}

templates/post/post_detail.html
{%extends 'base.html' %}
{% block title %}상세{% endblock %}

{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}
    

templates/post/post_form.html
{%extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1>Post 입력 화면</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="id_image">이미지</label>
            {% if post.image %}#}
                <p>현재 : <a href="{{ post.image.url }}">{{ post.image.name }}</a></p>
                <p>변경 : <input type="file" name="image" accept="image/*" id="id_image"></p>
            {% else %}
                <input type="file" name="image" accept="image/*" ida="id_image">
            {% endif %}
        </div>
        <div>
            <label for="id_content">내용</label>
            <textarea name="content" id="id_content" cols="30" rows="10">{% if post %}{{ post.content }}{% endif %}
            </textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
    <hr>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock}

templates/post/post_list.html
{%extends 'base.html' %}
{% block title %}목록{% endblock %}

{% block content %}
<h1>Post 목록</h1>
{{post_list}}
{% endblock}